#!/usr/bin/env bash
set -e

# Script to install language environments and generate sample package files on Debian 12 for SCALIBR extractor testing.
# Run with: sudo ./install_packages.sh

echo "===================================================="
echo "1. Installing base dependencies & Go"
echo "===================================================="
apt-get update -y
apt-get install -y curl wget git build-essential unzip jq time

# Install latest Go
GO_VERSION=$(curl -s https://go.dev/VERSION?m=text | head -n 1)
echo "Installing Go ${GO_VERSION}..."
curl -fsSL "https://go.dev/dl/${GO_VERSION}.linux-amd64.tar.gz" -o go.tar.gz
rm -rf /usr/local/go && tar -C /usr/local -xzf go.tar.gz
rm -f go.tar.gz
export PATH=$PATH:/usr/local/go/bin
echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile.d/go.sh

echo "===================================================="
echo "2. Installing Python & sample packages (python/wheelegg, python/uvlock)"
echo "===================================================="
apt-get install -y python3 python3-pip python3-setuptools
pip3 install --break-system-packages requests flask urllib3 || pip3 install requests flask urllib3

mkdir -p /opt/demo-python
cat << 'EOF' > /opt/demo-python/uv.lock
version = 1
revision = 1
manifest = "pyproject.toml"

[[package]]
name = "requests"
version = "2.31.0"
source = { registry = "https://pypi.org/simple" }
EOF

echo "===================================================="
echo "3. Installing Node.js & npm (javascript/packagejson)"
echo "===================================================="
apt-get install -y nodejs npm
mkdir -p /opt/demo-js
cd /opt/demo-js
npm init -y
npm install express lodash

echo "===================================================="
echo "4. Installing Ruby & gems (ruby/gemspec)"
echo "===================================================="
apt-get install -y ruby-full
gem install rake json || true

echo "===================================================="
echo "5. Installing PHP & Composer (php/composerlock)"
echo "===================================================="
apt-get install -y php-cli composer
mkdir -p /opt/demo-php
cat << 'EOF' > /opt/demo-php/composer.json
{
    "name": "demo/app",
    "require": {
        "guzzlehttp/guzzle": "^7.8"
    }
}
EOF
cat << 'EOF' > /opt/demo-php/composer.lock
{
    "_readme": [
        "This file locks the dependencies of your project to a known state"
    ],
    "content-hash": "d41d8cd98f00b204e9800998ecf8427e",
    "packages": [
        {
            "name": "guzzlehttp/guzzle",
            "version": "7.8.1",
            "source": { "type": "git", "url": "https://github.com/guzzle/guzzle.git", "reference": "3a0ee395869da7b732047138022d174a95299ccb" }
        }
    ]
}
EOF

echo "===================================================="
echo "6. Installing Rust & Cargo (rust/cargolock, rust/cargoauditable)"
echo "===================================================="
apt-get install -y cargo
mkdir -p /opt/demo-rust/src
cat << 'EOF' > /opt/demo-rust/Cargo.toml
[package]
name = "demo-rust"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0"
EOF
cat << 'EOF' > /opt/demo-rust/src/main.rs
fn main() { println!("Hello benchmark"); }
EOF
cat << 'EOF' > /opt/demo-rust/Cargo.lock
# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "demo-rust"
version = "0.1.0"

[[package]]
name = "serde"
version = "1.0.197"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3fb1c873e1b9ce60114213d875502a88498cd0c632e2d9b89569e5d4d3b664d4"
EOF

# Download precompiled cargo-auditable binary for instant setup
echo "Installing precompiled cargo-auditable..."
curl -fsSL https://github.com/rust-sec/cargo-auditable/releases/download/v0.6.2/cargo-auditable-x86_64-unknown-linux-musl.tar.gz -o /tmp/cargo-auditable.tar.gz || true
if [ -f /tmp/cargo-auditable.tar.gz ]; then
    tar -xzf /tmp/cargo-auditable.tar.gz -C /usr/local/bin cargo-auditable || true
    rm -f /tmp/cargo-auditable.tar.gz
fi

cd /opt/demo-rust
cargo build || true
if command -v cargo-auditable >/dev/null 2>&1; then
    cargo-auditable build || true
fi

echo "===================================================="
echo "7. Installing Java & sample manifest files (java/archive, java/pomxml, java/gradlelockfile)"
echo "===================================================="
apt-get install -y default-jdk
mkdir -p /opt/demo-java/gradle/dependency-locks
cat << 'EOF' > /opt/demo-java/pom.xml
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.demo</groupId>
  <artifactId>demo-app</artifactId>
  <version>1.0.0</version>
  <dependencies>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
      <version>5.3.23</version>
    </dependency>
  </dependencies>
</project>
EOF
cat << 'EOF' > /opt/demo-java/gradle.lockfile
# This is a Gradle lockfile
org.springframework:spring-core:5.3.23=compileClasspath,runtimeClasspath
EOF
cat << 'EOF' > /opt/demo-java/gradle/dependency-locks/gradle.lockfile
# This is a Gradle lockfile
org.springframework:spring-core:5.3.23=compileClasspath,runtimeClasspath
EOF

echo "===================================================="
echo "8. Generating sample Swift & Dart manifest files (swift/packageresolved, dart/pubspec)"
echo "===================================================="
mkdir -p /opt/demo-swift/DemoApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm
cat << 'EOF' > /opt/demo-swift/Package.resolved
{
  "version": 1,
  "object": {
    "pins": [
      {
        "package": "Alamofire",
        "repositoryURL": "https://github.com/Alamofire/Alamofire.git",
        "state": {
          "branch": null,
          "revision": "f455c297587245a230bf9f4e99c8d2d6330058b4",
          "version": "5.8.1"
        }
      }
    ]
  }
}
EOF
cp /opt/demo-swift/Package.resolved /opt/demo-swift/DemoApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

mkdir -p /opt/demo-dart
cat << 'EOF' > /opt/demo-dart/pubspec.lock
packages:
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dev"
    source: hosted
    version: "1.2.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
EOF

echo "===================================================="
echo "All language environments and sample packages successfully installed!"
echo "===================================================="
